# Training config for Resnet on ImageNet
# comment out target line here and write in terminal

arch: resnet18
# dataset: ImageNet1k
batch_size: 4
lr: 0.1
wd: 0.
cupy: true
lr_warmup_epochs: 10
val_resize_size: 232
val_crop_size: 224
train_crop_size: 176
opt: sgd